import {scale} from 'react-native-size-matters';

import Colors from '../../theme';

export default {
  containerView: {
    flex: 1,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    width: '100%',
  },

  dropShadow: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    width: '100%',
    minHeight: scale(80),
    paddingHorizontal: scale(18),
  },
  searchBtnView: {
    width: '100%',
    height: scale(45),
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'space-between',
    marginBottom: scale(15),
    marginTop: scale(18),
  },
  searchIconView: {
    flexDirection: 'row',
    width: '55%',
    borderWidth: 1,
    alignItems: 'center',
    borderRadius: scale(15),
    paddingHorizontal: scale(15),
    borderColor: Colors.lightRed,
  },
  searchInput: {
    width: '93%',
    borderWidth: 0,
    paddingHorizontal: scale(5),
  },
  mapView: {
    width: '95%',
    height: scale(250),
    alignSelf: 'center',
    marginBottom: scale(25),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.5,
    shadowRadius: 3,
  },
  saveBtnView: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    justifyContent: 'space-between',
    paddingHorizontal: scale(5),
  },
  submitBtn: {
    backgroundColor: Colors.grayishRed,
    paddingHorizontal: scale(25),
    marginLeft: scale(10),
    width: scale(150),
  },
  cancelBtn: {
    width: scale(111),
    backgroundColor: null,
    alignItems: 'flex-start',
  },
  addPosiBtn: {
    paddingHorizontal: scale(28),
    backgroundColor: Colors.blackPearl,
    top: scale(5),
  },
  massDelTxt: {fontSize: scale(11)},
  addEmpLabelStyle: {
    fontSize: scale(12),
    color: Colors.blackPearl,
    textAlign: 'left',
  },
  labelStyle: {marginLeft: scale(-10)},
  keyboardAwareScrollView: {flex: 0.92, paddingHorizontal: scale(18)},

  branchNameView: {
    flexDirection: 'row',
    width: '100%',
    height: scale(30),
    alignItems: 'center',
  },
  branchNameTxt: {
    fontSize: scale(12),
    color: Colors.blackPearl,
    fontWeight: '600',
    width: '30%',
  },
  dotView: {
    borderTopWidth: 1,
    borderStyle: 'dotted',
    width: '43%',
    top: scale(2),
    alignSelf: 'center',
  },
  branchNameTxt1: {
    fontSize: scale(12),
    color: '#666',
    fontWeight: '600',
    width: '24%',
    marginLeft: scale(3),
    textAlign: 'right',
  },
  left: {marginLeft: scale(3)},
  width53: {width: '53%'},
  width15: {width: '15%'},
  width30: {width: '30%'},
  width40: {width: '40%'},
  width43: {width: '43%'},
  width20: {width: '20%'},
  width48: {width: '48%'},

  headerMainView: {
    height: scale(60),
    backgroundColor: Colors.blackPearl,
    paddingHorizontal: scale(15),
    justifyContent: 'center',
  },
  headerStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerDate: {
    width: scale(115),
    height: '100%',
    justifyContent: 'center',
  },
  headerBouns: {
    width: scale(130),
    height: '100%',
    justifyContent: 'center',
  },
  userNameTxt: {
    fontSize: scale(10),
    color: Colors.white,
    fontWeight: '500',
  },
  iconMainView: {
    width: scale(150),
    height: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  emptyView: {width: scale(30)},
  checkBoxView: {
    width: scale(20),
    height: scale(20),
    borderWidth: 1,
    borderRadius: scale(5),
  },
  tbView: {paddingHorizontal: scale(15), height: scale(50)},
  sBlack: {color: Colors.sBlack},
  top: {marginTop: scale(12)},
  emptyView1: {width: scale(23), height: '100%', justifyContent: 'center'},

  userNameTxt1: {
    fontSize: scale(10),
    color: Colors.sBlack,
    fontWeight: '500',
    width: '35%',
  },
  modalIconMainView: {
    width: '95%',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    height: scale(60),
    marginTop: scale(15),
  },
  modalView: {
    flexDirection: 'row',
    width: '100%',
    height: scale(25),
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  editIconView: {
    width: scale(40),
    height: scale(40),
    borderRadius: scale(10),
    backgroundColor: Colors.blackPearl,
    justifyContent: 'center',
    alignItems: 'center',
  },

  width80: {width: scale(80)},
};
